import{useCallback,useEffect,useMemo,useState}from"react";
import{decideApproval,getOverview,getPendingApprovals,setPaused,submitMission}from"./lib/tauri";
import type{ApprovalRequest,CapabilitySnapshot,RuntimeMission,RuntimeOverview}from"./lib/types";

const pct=(v?:number|null)=>v==null?"—":`${Math.round(v)}%`;const temp=(v?:number|null)=>v==null?"—":`${Math.round(v)}°`;
function Cap({item}:{item:CapabilitySnapshot}){return <div className={`capability capability-${item.state}`} title={item.evidence}><span className="capability-dot"/><span>{item.label}</span><b>{item.state.toUpperCase()}</b></div>}

export default function App(){
 const[overview,setOverview]=useState<RuntimeOverview|null>(null);const[command,setCommand]=useState("");const[mission,setMission]=useState<RuntimeMission|null>(null);const[approvals,setApprovals]=useState<ApprovalRequest[]>([]);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{try{const[o,a]=await Promise.all([getOverview(),getPendingApprovals()]);setOverview(o);setApprovals(a);setError(null)}catch(e){setError(String(e))}},[]);
 useEffect(()=>{refresh();const t=setInterval(refresh,2500);return()=>clearInterval(t)},[refresh]);
 const device=overview?.device,runtime=overview?.runtime,cDisk=device?.disks.find(d=>d.mount.toUpperCase().startsWith("C:"))??device?.disks[0];
 const diskPct=cDisk?((cDisk.totalGb-cDisk.freeGb)/cDisk.totalGb)*100:null;const readiness=useMemo(()=>{if(!device)return 0;let s=100;if(device.ramUsagePercent>85)s-=15;if(device.cpuUsagePercent>90)s-=10;if((device.gpu?.temperatureC??0)>85)s-=15;if(cDisk&&cDisk.freeGb<20)s-=10;return Math.max(0,s)},[device,cDisk]);
 const run=async()=>{const goal=command.trim();if(!goal||busy)return;setBusy(true);setError(null);try{const m=await submitMission(goal);setMission(m);setCommand("");await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
 const decide=async(id:string,approve:boolean)=>{setBusy(true);setError(null);try{setMission(await decideApproval(id,approve));await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
 const toggle=async()=>{if(!runtime)return;await setPaused(!runtime.paused);await refresh()};
 const activeText=runtime?.paused?"متوقف بأمان":mission?({planning:"يفهم الهدف",running:"ينفذ المهمة",verifying:"يتحقق من النتيجة",waiting_approval:"ينتظر موافقتك",completed:"المهمة مكتملة ومتحققة",cancelled:"المهمة ألغيت"}[mission.status]??mission.status):"يراقب الجهاز بصمت";
 return <main className="shell"><div className="ambient ambient-a"/><div className="ambient ambient-b"/>
  <header className="topbar"><div className="brand"><div className="brand-orb"/><div><b>D7 BLACKCORE</b><small>PERSONAL AUTONOMOUS OS · 2.0 dev.6</small></div></div><div className="top-actions"><span className="status-chip native"><i/> NATIVE RUNTIME</span><span className="status-chip elite">ELITE</span><button className={`stop ${runtime?.paused?"paused":""}`} onClick={toggle}>{runtime?.paused?"استئناف":"إيقاف"}</button></div></header>
  <section className="hero glass"><div className="hero-copy"><span className="eyebrow">MISSION RUNTIME · APPROVAL FIREWALL · EVIDENCE</span><h1>وش تبي أسوي؟</h1><p>{device?`${device.hostname} · ${device.os} · ${runtime?.version}`:"جارٍ تشغيل Runtime..."}</p></div><div className="command-row"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} placeholder="اكتب الهدف فقط..."/><button onClick={run} disabled={busy}>{busy?"يعمل...":"ابدأ"}</button></div><div className="quick-actions"><button onClick={()=>setCommand("افحص جهازي كامل")}>⚡ افحص الجهاز</button><button onClick={()=>setCommand("أنشئ مجلد على سطح المكتب باسم BLACKCORE_TEST، وداخله ملف result.txt واكتب فيه: D7 BLACKCORE WORKS")}>✅ اختبار تنفيذ</button><button onClick={()=>setCommand("أبي ألعب رانك كود")}>🎮 رانك</button><button onClick={()=>setCommand("ابنِ لي برنامج احترافي")}>🛠 Builder</button><button onClick={()=>setCommand("أبي أطلع دخل من الإنترنت")}>💰 Money</button></div><div className="metrics-strip"><div><span>CPU</span><b>{pct(device?.cpuUsagePercent)}</b></div><div><span>RAM</span><b>{pct(device?.ramUsagePercent)}</b></div><div><span>GPU</span><b>{pct(device?.gpu?.utilizationPercent)}</b></div><div><span>TEMP</span><b>{temp(device?.gpu?.temperatureC)}</b></div><div><span>C:</span><b>{diskPct==null?"—":`${Math.round(diskPct)}% مستخدم`}</b></div></div></section>
  {error&&<div className="error-banner">{error}</div>}
  <section className="cards-grid"><article className="glass card active-card"><span className="card-label">وش يسوي الآن؟</span><h2>{activeText}</h2><p>{mission?.goal??"جاهز لهدف جديد."}</p><div className="pulse-line"><span/></div></article><article className="glass card"><span className="card-label">الجهاز</span><h2>{readiness}% جاهز</h2><p>{device?`${device.cpuName} · RAM ${device.ramTotalGb.toFixed(1)} GB · ${device.gpu?.name??"GPU غير مقروء"}`:"—"}</p><span className="mini-tag">LIVE DEVICE TWIN</span></article><article className="glass card"><span className="card-label">الموافقات</span><h2>{approvals.length}</h2><p>{approvals.length?"في إجراء حساس ينتظر قرارك.":"لا يوجد إجراء حساس معلق."}</p><span className="mini-tag">APPROVAL FIREWALL</span></article><article className="glass card"><span className="card-label">الدخل</span><h2>$0 مؤكد</h2><p>لا نحسب دخل بدون Payment Proof.</p><span className="mini-tag">PAYMENT PROOF</span></article></section>
  {approvals.map(a=><section className="glass approval-box" key={a.id}><div><span>موافقة مطلوبة · {a.risk.toUpperCase()}</span><h3>{a.reason}</h3><p>{a.targetPath}</p></div><div className="approval-actions"><button className="reject" onClick={()=>decide(a.id,false)} disabled={busy}>رفض</button><button className="approve" onClick={()=>decide(a.id,true)} disabled={busy}>موافقة + Checkpoint</button></div></section>)}
  {mission?.result&&<section className="lower-grid mission-grid"><article className="glass capabilities-panel"><div className="section-title"><div><span>MISSION PROOF</span><h3>{mission.result.verified?"VERIFIED":"FAILED"} · {mission.result.qualityScore}%</h3></div></div><div className="runtime-rows">{mission.result.steps.map((s,i)=><div key={i}><span>{s.title}</span><b className={s.status==="completed"?"ok":"muted"}>{s.status}</b></div>)}<div><span>المسار</span><b>{mission.result.targetPath??"—"}</b></div></div></article><article className="glass runtime-panel"><div className="section-title"><div><span>EVIDENCE</span><h3>الدليل</h3></div></div><div className="runtime-rows">{mission.result.evidence.map((e,i)=><div key={i}><span>{e.claim}</span><b className={e.verified?"ok":"muted"}>{e.verified?"VERIFIED":"FAILED"}</b></div>)}</div></article></section>}
  <section className="lower-grid"><article className="glass capabilities-panel"><div className="section-title"><div><span>CAPABILITY TRUTH</span><h3>القدرات المثبتة الآن</h3></div><button onClick={refresh}>تحديث</button></div><div className="capabilities-list">{overview?.capabilities.map(x=><Cap item={x} key={x.id}/>)}</div></article><article className="glass runtime-panel"><div className="section-title"><div><span>LIVE SYSTEM</span><h3>D7 + Models</h3></div></div><div className="runtime-rows"><div><span>OpenCode</span><b className={device?.openCode.available?"ok":"muted"}>{device?.openCode.available?`ONLINE ${device.openCode.version??""}`:"OFFLINE"}</b></div><div><span>D7 Governor</span><b className={device?.governor.available?"ok":"muted"}>{device?.governor.available?device.governor.state??"CONNECTED":"NOT FOUND"}</b></div><div><span>Processes</span><b>{device?.processCount??"—"}</b></div><div><span>نشط</span><b>{device?.runningApps.join(" · ")||"—"}</b></div></div></article></section><footer>BLACKCORE 2.0 dev.6 · Mission Runtime · Journal · Approval · Checkpoint</footer>
 </main>}
