import { useCallback, useEffect, useMemo, useState } from "react";
import { decideApproval, getOverview, getPendingApprovals, setPaused, submitMission } from "./lib/tauri";
import type { ApprovalRequest, CapabilitySnapshot, RuntimeMission, RuntimeOverview } from "./lib/types";

const pct=(v?:number|null)=>v==null?"—":`${Math.round(v)}%`;
const temp=(v?:number|null)=>v==null?"—":`${Math.round(v)}°`;
function Cap({item}:{item:CapabilitySnapshot}){return <div className={`capability capability-${item.state}`} title={item.evidence}><span className="capability-dot"/><span>{item.label}</span><b>{item.state.toUpperCase()}</b></div>}

export default function App(){
  const[overview,setOverview]=useState<RuntimeOverview|null>(null);
  const[command,setCommand]=useState("");
  const[mission,setMission]=useState<RuntimeMission|null>(null);
  const[approvals,setApprovals]=useState<ApprovalRequest[]>([]);
  const[error,setError]=useState<string|null>(null);
  const[busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{try{const[o,a]=await Promise.all([getOverview(),getPendingApprovals()]);setOverview(o);setApprovals(a);setError(null)}catch(e){setError(String(e))}},[]);
  useEffect(()=>{refresh();const t=window.setInterval(refresh,2500);return()=>window.clearInterval(t)},[refresh]);
  const d=overview?.device,r=overview?.runtime,g=d?.governor,agent=d?.legacyAgent,protocol=agent?.protocol;
  const cDisk=d?.disks.find(x=>x.mount.toUpperCase().startsWith("C:"))??d?.disks[0];
  const readiness=useMemo(()=>{if(!d)return 0;let s=100;if(d.ramUsagePercent>85)s-=15;if(d.cpuUsagePercent>90)s-=10;if((d.gpu?.temperatureC??0)>85)s-=15;if(cDisk&&cDisk.freeGb<20)s-=10;return Math.max(0,s)},[d,cDisk]);
  const active=r?.paused?"متوقف بأمان":mission?({planning:"يفهم الهدف",running:"ينفذ المهمة",verifying:"يتحقق من النتيجة",waiting_approval:"ينتظر موافقتك",completed:"المهمة مكتملة ومتحققة",cancelled:"المهمة ألغيت"}[mission.status]??mission.status):"يراقب الجهاز بصمت";
  async function run(){const goal=command.trim();if(!goal||busy)return;setBusy(true);setError(null);try{setMission(await submitMission(goal));setCommand("");await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
  async function decide(id:string,approve:boolean){setBusy(true);try{setMission(await decideApproval(id,approve));await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
  async function toggle(){if(!r)return;await setPaused(!r.paused);await refresh()}

  return <main className="shell">
    <div className="ambient ambient-a"/><div className="ambient ambient-b"/>
    <header className="topbar"><div className="brand"><div className="brand-orb"/><div><b>D7 BLACKCORE</b><small>PERSONAL AUTONOMOUS OS · {r?.version??"BOOTING"}</small></div></div><div className="top-actions"><span className="status-chip native"><i/> NATIVE RUNTIME</span><span className="status-chip elite">ELITE</span><button className={`stop ${r?.paused?"paused":""}`} onClick={toggle}>{r?.paused?"استئناف":"إيقاف"}</button></div></header>

    <section className="hero glass"><div className="hero-copy"><span className="eyebrow">NATIVE HOST · D7 CORE BRIDGE · GOVERNOR · EVIDENCE</span><h1>وش تبي أسوي؟</h1><p>{d?`${d.hostname} · ${d.os} · ${r?.version}`:"جارٍ تشغيل Runtime..."}</p></div><div className="command-row"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} placeholder="اكتب الهدف فقط..."/><button onClick={run} disabled={busy}>{busy?"يعمل...":"ابدأ"}</button></div><div className="quick-actions"><button onClick={()=>setCommand("افحص جهازي كامل")}>⚡ افحص الجهاز</button><button onClick={()=>setCommand("أنشئ مجلد على سطح المكتب باسم BLACKCORE_TEST، وداخله ملف result.txt واكتب فيه: D7 BLACKCORE WORKS")}>✅ اختبار تنفيذ</button><button onClick={()=>setCommand("أبي ألعب رانك كود")}>🎮 رانك</button><button onClick={()=>setCommand("ابنِ لي برنامج احترافي")}>🛠 Builder</button><button onClick={()=>setCommand("أبي أطلع دخل من الإنترنت")}>💰 Money</button></div><div className="metrics-strip"><div><span>CPU</span><b>{pct(g?.cpuPercent??d?.cpuUsagePercent)}</b></div><div><span>RAM</span><b>{pct(g?.ramPercent??d?.ramUsagePercent)}</b></div><div><span>GPU</span><b>{pct(g?.gpuPercent??d?.gpu?.utilizationPercent)}</b></div><div><span>TEMP</span><b>{temp(g?.gpuTempC??d?.gpu?.temperatureC)}</b></div><div><span>MODE</span><b>{g?.state??"—"}</b></div></div></section>
    {error&&<div className="error-banner">{error}</div>}

    <section className="cards-grid"><article className="glass card active-card"><span className="card-label">وش يسوي الآن؟</span><h2>{active}</h2><p>{mission?.goal??"جاهز لهدف جديد."}</p><div className="pulse-line"><span/></div></article><article className="glass card"><span className="card-label">الجهاز</span><h2>{readiness}% جاهز</h2><p>{g?.foregroundGame?`Game: ${g.foregroundGame} · ${g.detectionConfidence??"—"}%`:d?.cpuName??"—"}</p><span className="mini-tag">LIVE DEVICE TWIN</span></article><article className="glass card"><span className="card-label">D7 Core القديم</span><h2>{agent?.requestPipeAvailable&&agent?.eventPipeAvailable?"ONLINE":agent?.sourceAvailable?"FOUND":"OFFLINE"}</h2><p>{protocol?.sourceAvailable?`Protocol inspected · ${protocol.handlerCandidates.length} handlers`:agent?.sourceAvailable?"المصدر موجود؛ ننتظر pipe_server.py":"غير مكتشف"}</p><span className="mini-tag">LEGACY BRIDGE</span></article><article className="glass card"><span className="card-label">الموافقات</span><h2>{approvals.length}</h2><p>{approvals.length?"إجراء حساس ينتظر قرارك.":"لا يوجد إجراء حساس معلق."}</p><span className="mini-tag">APPROVAL FIREWALL</span></article></section>

    {approvals.map(a=><section className="glass approval-box" key={a.id}><div><span>موافقة مطلوبة · {a.risk.toUpperCase()}</span><h3>{a.reason}</h3><p>{a.targetPath}</p></div><div className="approval-actions"><button className="reject" onClick={()=>decide(a.id,false)} disabled={busy}>رفض</button><button className="approve" onClick={()=>decide(a.id,true)} disabled={busy}>موافقة + Checkpoint</button></div></section>)}

    {mission?.result&&<section className="lower-grid"><article className="glass capabilities-panel"><div className="section-title"><div><span>MISSION PROOF</span><h3>{mission.result.verified?"VERIFIED":"FAILED"} · {mission.result.qualityScore}%</h3></div></div><div className="runtime-rows">{mission.result.steps.map((s,i)=><div key={i}><span>{s.title}</span><b className={s.status==="completed"?"ok":"muted"}>{s.status}</b></div>)}<div><span>المسار</span><b>{mission.result.targetPath??"—"}</b></div></div></article><article className="glass runtime-panel"><div className="section-title"><div><span>EVIDENCE</span><h3>الدليل</h3></div></div><div className="runtime-rows">{mission.result.evidence.map((e,i)=><div key={i}><span>{e.claim}</span><b className={e.verified?"ok":"muted"}>{e.verified?"VERIFIED":"FAILED"}</b></div>)}</div></article></section>}

    <section className="lower-grid"><article className="glass capabilities-panel"><div className="section-title"><div><span>CAPABILITY TRUTH</span><h3>القدرات المثبتة الآن</h3></div><button onClick={refresh}>تحديث</button></div><div className="capabilities-list">{overview?.capabilities.map(x=><Cap item={x} key={x.id}/>)}</div></article><article className="glass runtime-panel"><div className="section-title"><div><span>LIVE SYSTEM</span><h3>D7 + Models</h3></div></div><div className="runtime-rows"><div><span>D7 Request Pipe</span><b className={agent?.requestPipeAvailable?"ok":"muted"}>{agent?.requestPipeAvailable?"ONLINE":"OFFLINE"}</b></div><div><span>D7 Event Pipe</span><b className={agent?.eventPipeAvailable?"ok":"muted"}>{agent?.eventPipeAvailable?"ONLINE":"OFFLINE"}</b></div><div><span>Governor</span><b className={g?.available?"ok":"muted"}>{g?.available?`${g.state} · CPU Guard ${g.cpuGuardMode??"—"}`:"NOT FOUND"}</b></div><div><span>Ping</span><b>{g?.internetPingMs==null?"—":`${g.internetPingMs} ms`}</b></div><div><span>OpenCode</span><b className={d?.openCode.available?"ok":"muted"}>{d?.openCode.available?`ONLINE ${d.openCode.version??""}`:"OFFLINE"}</b></div></div></article></section>

    <section className="lower-grid"><article className="glass capabilities-panel"><div className="section-title"><div><span>LEGACY PROTOCOL</span><h3>Protocol Inspector</h3></div></div><div className="runtime-rows"><div><span>pipe_server.py</span><b className={protocol?.sourceAvailable?"ok":"muted"}>{protocol?.sourceAvailable?"INSPECTED":"NOT FOUND"}</b></div><div><span>Fingerprint</span><b>{protocol?.sourceFingerprint??"—"}</b></div><div><span>Source lines</span><b>{protocol?.lineCount??0}</b></div><div><span>Handlers</span><b>{protocol?.handlerCandidates.slice(0,6).join(" · ")||"—"}</b></div><div><span>Framing signals</span><b>{protocol?.framingSignals.length??0}</b></div><div><span>Protocol signals</span><b>{protocol?.protocolSignals.length??0}</b></div></div></article><article className="glass runtime-panel"><div className="section-title"><div><span>D7 GOVERNOR</span><h3>الحالة الفعلية</h3></div></div><div className="runtime-rows"><div><span>Game</span><b>{g?.foregroundGame??"—"}</b></div><div><span>Detection</span><b>{g?.detectionReason??"—"} {g?.detectionConfidence==null?"":`${g.detectionConfidence}%`}</b></div><div><span>HAGS</span><b>{g?.hags??"—"}</b></div><div><span>Restrained</span><b>{g?.restrainedProcesses.join(" · ")||"—"}</b></div></div></article></section>
    <footer>BLACKCORE · Native Mission Runtime · D7 Legacy Protocol Evidence · NO CLAIM WITHOUT PROOF</footer>
  </main>
}
