<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>D7.Blackcore</AssemblyName>
    <RootNamespace>D7.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\D7.Core\D7.Core.csproj" />
    <ProjectReference Include="..\D7.Hardware\D7.Hardware.csproj" />
    <ProjectReference Include="..\D7.Games\D7.Games.csproj" />
    <ProjectReference Include="..\D7.Tools\D7.Tools.csproj" />
    <ProjectReference Include="..\D7.Benchmark\D7.Benchmark.csproj" />
    <ProjectReference Include="..\D7.Rollback\D7.Rollback.csproj" />
    <ProjectReference Include="..\D7.Optimization\D7.Optimization.csproj" />
    <ProjectReference Include="..\D7.Orchestration\D7.Orchestration.csproj" />
  </ItemGroup>
</Project>
