use crate::legacy::{probe_legacy_agent, LegacyAgentSnapshot};
use serde::Serialize;
use std::{fs, io::{Read,Write}, net::{SocketAddr,TcpStream}, path::Path, process::Command, time::Duration};
use sysinfo::{Disks,System};
#[cfg(target_os="windows")]use std::os::windows::process::CommandExt;

#[derive(Debug,Clone,Serialize)]#[serde(rename_all="camelCase")]pub struct GpuSnapshot{pub name:String,pub utilization_percent:Option<f32>,pub temperature_c:Option<f32>,pub memory_used_mb:Option<f32>,pub memory_total_mb:Option<f32>}
#[derive(Debug,Clone,Serialize)]#[serde(rename_all="camelCase")]pub struct DiskSnapshot{pub mount:String,pub total_gb:f64,pub free_gb:f64}
#[derive(Debug,Clone,Serialize)]#[serde(rename_all="camelCase")]pub struct GovernorSnapshot{pub available:bool,pub state:Option<String>,pub source:Option<String>,pub foreground_game:Option<String>,pub detection_reason:Option<String>,pub detection_confidence:Option<f64>,pub cpu_percent:Option<f64>,pub ram_percent:Option<f64>,pub gpu_percent:Option<f64>,pub gpu_temp_c:Option<f64>,pub gateway_ping_ms:Option<f64>,pub internet_ping_ms:Option<f64>,pub cpu_guard_mode:Option<String>,pub restrained_processes:Vec<String>,pub hags:Option<String>}
#[derive(Debug,Clone,Serialize)]#[serde(rename_all="camelCase")]pub struct OpenCodeSnapshot{pub available:bool,pub version:Option<String>,pub endpoint:String}
#[derive(Debug,Clone,Serialize)]#[serde(rename_all="camelCase")]pub struct DeviceSnapshot{pub captured_at:String,pub hostname:String,pub os:String,pub cpu_name:String,pub cpu_usage_percent:f32,pub logical_cpus:usize,pub ram_total_gb:f64,pub ram_used_gb:f64,pub ram_usage_percent:f64,pub gpu:Option<GpuSnapshot>,pub disks:Vec<DiskSnapshot>,pub process_count:usize,pub running_apps:Vec<String>,pub governor:GovernorSnapshot,pub open_code:OpenCodeSnapshot,pub legacy_agent:LegacyAgentSnapshot}
fn now_iso()->String{format!("{}",std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs())}
fn gb(v:u64)->f64{v as f64/1024.0/1024.0/1024.0}
fn gpu()->Option<GpuSnapshot>{let mut c=Command::new("nvidia-smi");c.args(["--query-gpu=name,utilization.gpu,temperature.gpu,memory.used,memory.total","--format=csv,noheader,nounits"]);#[cfg(target_os="windows")]c.creation_flags(0x08000000);let o=c.output().ok()?;if!o.status.success(){return None}let line=String::from_utf8_lossy(&o.stdout).lines().next()?.trim().to_string();let p:Vec<_>=line.split(',').map(|x|x.trim()).collect();if p.len()<5{return None}Some(GpuSnapshot{name:p[0].into(),utilization_percent:p[1].parse().ok(),temperature_c:p[2].parse().ok(),memory_used_mb:p[3].parse().ok(),memory_total_mb:p[4].parse().ok()})}
fn strv(v:&serde_json::Value,k:&str)->Option<String>{v.get(k)?.as_str().map(str::to_owned)}fn num(v:&serde_json::Value,k:&str)->Option<f64>{v.get(k)?.as_f64()}
fn governor()->GovernorSnapshot{let path=r"C:\ProgramData\D7PerformanceGovernor\status.json";let empty=||GovernorSnapshot{available:false,state:None,source:None,foreground_game:None,detection_reason:None,detection_confidence:None,cpu_percent:None,ram_percent:None,gpu_percent:None,gpu_temp_c:None,gateway_ping_ms:None,internet_ping_ms:None,cpu_guard_mode:None,restrained_processes:vec![],hags:None};if!Path::new(path).exists(){return empty()}let raw=match fs::read_to_string(path){Ok(v)=>v,Err(_)=>{let mut x=empty();x.available=true;x.state=Some("READ_ERROR".into());x.source=Some(path.into());return x}};let v:serde_json::Value=serde_json::from_str(&raw).unwrap_or_default();GovernorSnapshot{available:true,state:strv(&v,"state").or(Some("CONNECTED".into())),source:Some(path.into()),foreground_game:strv(&v,"foregroundGame"),detection_reason:strv(&v,"gameDetectionReason"),detection_confidence:num(&v,"gameDetectionConfidence"),cpu_percent:num(&v,"cpuPercent"),ram_percent:num(&v,"ramPercent"),gpu_percent:num(&v,"gpuPercent"),gpu_temp_c:num(&v,"gpuTempC"),gateway_ping_ms:num(&v,"gatewayPingMs"),internet_ping_ms:num(&v,"internetPingMs"),cpu_guard_mode:strv(&v,"cpuGuardMode"),restrained_processes:v.get("restrainedProcesses").and_then(|x|x.as_array()).map(|a|a.iter().filter_map(|x|x.as_str().map(str::to_owned)).collect()).unwrap_or_default(),hags:strv(&v,"hags")}}
fn opencode()->OpenCodeSnapshot{let endpoint="http://127.0.0.1:8082".to_string();let addr:SocketAddr="127.0.0.1:8082".parse().unwrap();let mut s=match TcpStream::connect_timeout(&addr,Duration::from_millis(350)){Ok(v)=>v,Err(_)=>return OpenCodeSnapshot{available:false,version:None,endpoint}};let _=s.set_read_timeout(Some(Duration::from_millis(500)));if s.write_all(b"GET /global/health HTTP/1.1\r\nHost: 127.0.0.1:8082\r\nConnection: close\r\n\r\n").is_err(){return OpenCodeSnapshot{available:false,version:None,endpoint}}let mut r=String::new();if s.read_to_string(&mut r).is_err(){return OpenCodeSnapshot{available:false,version:None,endpoint}}let available=r.contains("200 OK")&&r.contains("healthy");let version=r.split("\r\n\r\n").nth(1).and_then(|b|serde_json::from_str::<serde_json::Value>(b).ok()).and_then(|v|v.get("version").and_then(|x|x.as_str()).map(str::to_owned));OpenCodeSnapshot{available,version,endpoint}}
pub fn collect_device_snapshot()->DeviceSnapshot{let mut sys=System::new_all();std::thread::sleep(Duration::from_millis(120));sys.refresh_all();let total=sys.total_memory();let used=sys.used_memory();let names:Vec<String>=sys.processes().values().map(|p|p.name().to_string_lossy().to_ascii_lowercase()).collect();let mut apps=vec![];for(label,aliases)in[("chrome",["chrome.exe","chrome"]),("discord",["discord.exe","discord"]),("obs",["obs64.exe","obs64"]),("tiktok live studio",["tiktok live studio.exe","tiktok_live_studio.exe"]),("steam",["steam.exe","steam"]),("opencode",["opencode.exe","opencode"]) ]{if aliases.iter().any(|a|names.iter().any(|p|p==a)){apps.push(label.into())}}let disks=Disks::new_with_refreshed_list().iter().map(|d|DiskSnapshot{mount:d.mount_point().to_string_lossy().to_string(),total_gb:gb(d.total_space()),free_gb:gb(d.available_space())}).collect();DeviceSnapshot{captured_at:now_iso(),hostname:System::host_name().unwrap_or_else(||"Windows PC".into()),os:format!("{} {}",System::name().unwrap_or_else(||"Windows".into()),System::os_version().unwrap_or_default()).trim().into(),cpu_name:sys.cpus().first().map(|c|c.brand().into()).unwrap_or_else(||"Unknown CPU".into()),cpu_usage_percent:sys.global_cpu_usage(),logical_cpus:sys.cpus().len(),ram_total_gb:gb(total),ram_used_gb:gb(used),ram_usage_percent:if total>0{used as f64/total as f64*100.0}else{0.0},gpu:gpu(),disks,process_count:sys.processes().len(),running_apps:apps,governor:governor(),open_code:opencode(),legacy_agent:probe_legacy_agent()}}
