use serde::Serialize;
use std::{env, fs, path::{Path, PathBuf}, time::{SystemTime, UNIX_EPOCH}};

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MissionStepResult { pub title:String, pub status:String, pub evidence:Option<String> }
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MissionEvidence { pub kind:String, pub claim:String, pub value:String, pub verified:bool }
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MissionResult { pub id:String, pub goal:String, pub status:String, pub quality_score:u8, pub target_path:Option<String>, pub verified:bool, pub steps:Vec<MissionStepResult>, pub evidence:Vec<MissionEvidence> }

fn mission_id()->String{format!("mission-{}",SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos())}
fn valid_component(v:&str)->bool{let v=v.trim();!v.is_empty()&&v.len()<=120&&v!="."&&v!=".."&&!v.chars().any(|c|matches!(c,'\\'|'/'|':'|'*'|'?'|'"'|'<'|'>'|'|'))}
fn extract_between<'a>(text:&'a str,start:&str,stops:&[&str])->Option<&'a str>{let offset=text.find(start)?+start.len();let tail=&text[offset..];let mut end=tail.len();for stop in stops{if let Some(i)=tail.find(stop){end=end.min(i);}}let value=tail[..end].trim();(!value.is_empty()).then_some(value)}
fn parse_goal(goal:&str)->Result<(String,String,String),String>{let folder=extract_between(goal,"باسم ",&["،",","," وداخله"," وداخله ملف","\n"]).or_else(||extract_between(goal,"folder named ",&[","," and","\n"])).ok_or("FAST_PATH_FOLDER_NAME_NOT_FOUND")?;let file=extract_between(goal,"ملف ",&[" واكتب","،",",","\n"]).or_else(||extract_between(goal,"file ",&[" and write",",","\n"])).ok_or("FAST_PATH_FILE_NAME_NOT_FOUND")?;let content=goal.split_once("اكتب فيه:").map(|(_,v)|v.trim()).or_else(||goal.split_once("write:").map(|(_,v)|v.trim())).ok_or("FAST_PATH_CONTENT_NOT_FOUND")?;if !valid_component(folder){return Err("UNSAFE_FOLDER_NAME".into())}if !valid_component(file){return Err("UNSAFE_FILE_NAME".into())}if content.len()>100_000{return Err("CONTENT_TOO_LARGE".into())}Ok((folder.into(),file.into(),content.into()))}
fn desktop_root()->Result<PathBuf,String>{let home=env::var("USERPROFILE").map_err(|_|"USERPROFILE_NOT_FOUND".to_string())?;let p=Path::new(&home).join("Desktop");if !p.exists(){return Err("DESKTOP_NOT_FOUND".into())}Ok(p)}
pub fn target_path_for_goal(goal:&str)->Result<PathBuf,String>{let(f,file,_)=parse_goal(goal)?;Ok(desktop_root()?.join(f).join(file))}

fn execute_at_root(root:&Path,goal:&str,allow_overwrite:bool)->Result<MissionResult,String>{let id=mission_id();let(folder_name,file_name,content)=parse_goal(goal)?;let folder=root.join(folder_name);let file=folder.join(file_name);let mut steps=vec![MissionStepResult{title:"فهم الهدف وتقييد المسار".into(),status:"completed".into(),evidence:Some(root.display().to_string())},MissionStepResult{title:"إنشاء المجلد".into(),status:"pending".into(),evidence:None},MissionStepResult{title:"كتابة الملف".into(),status:"pending".into(),evidence:None},MissionStepResult{title:"إعادة قراءة الملف والتحقق".into(),status:"pending".into(),evidence:None}];if file.exists()&&!allow_overwrite{return Err(format!("APPROVAL_REQUIRED_EXISTING_TARGET:{}",file.display()))}fs::create_dir_all(&folder).map_err(|e|format!("CREATE_DIR_FAILED:{e}"))?;steps[1].status="completed".into();steps[1].evidence=Some(folder.display().to_string());fs::write(&file,content.as_bytes()).map_err(|e|format!("WRITE_FILE_FAILED:{e}"))?;steps[2].status="completed".into();steps[2].evidence=Some(format!("{} bytes",content.len()));let read_back=fs::read_to_string(&file).map_err(|e|format!("VERIFY_READ_FAILED:{e}"))?;if read_back!=content{return Err("VERIFY_CONTENT_MISMATCH".into())}steps[3].status="completed".into();steps[3].evidence=Some(read_back.clone());Ok(MissionResult{id,goal:goal.into(),status:"completed".into(),quality_score:100,target_path:Some(file.display().to_string()),verified:true,steps,evidence:vec![MissionEvidence{kind:"file".into(),claim:"Target file exists".into(),value:file.display().to_string(),verified:file.exists()},MissionEvidence{kind:"test".into(),claim:"Read-back content matches requested content".into(),value:read_back,verified:true}]})}
pub fn execute_fast_path_with_policy(goal:&str,allow_overwrite:bool,_checkpoint:Option<&Path>)->Result<MissionResult,String>{execute_at_root(&desktop_root()?,goal,allow_overwrite)}
pub fn execute_fast_path(goal:&str)->Result<MissionResult,String>{execute_fast_path_with_policy(goal,false,None)}

#[cfg(test)]mod tests{use super::*;fn root()->PathBuf{env::temp_dir().join(mission_id())}#[test]fn parses_arabic(){let p=parse_goal("أنشئ مجلد على سطح المكتب باسم BLACKCORE_TEST، وداخله ملف result.txt واكتب فيه: D7 BLACKCORE WORKS").unwrap();assert_eq!(p.0,"BLACKCORE_TEST");assert_eq!(p.1,"result.txt");assert_eq!(p.2,"D7 BLACKCORE WORKS");}#[test]fn rejects_traversal(){assert!(!valid_component(".."));assert!(!valid_component("a/b"));assert!(!valid_component("a\\b"));}#[test]fn real_write_verify(){let r=root();fs::create_dir_all(&r).unwrap();let goal="أنشئ مجلد على سطح المكتب باسم BLACKCORE_TEST، وداخله ملف result.txt واكتب فيه: D7 BLACKCORE WORKS";let result=execute_at_root(&r,goal,false).unwrap();assert!(result.verified);assert_eq!(fs::read_to_string(result.target_path.unwrap()).unwrap(),"D7 BLACKCORE WORKS");fs::remove_dir_all(r).unwrap();}#[test]fn overwrite_guard_and_approved_path(){let r=root();let f=r.join("BLACKCORE_TEST");fs::create_dir_all(&f).unwrap();let target=f.join("result.txt");fs::write(&target,"ORIGINAL").unwrap();let goal="أنشئ مجلد على سطح المكتب باسم BLACKCORE_TEST، وداخله ملف result.txt واكتب فيه: REPLACEMENT";assert!(execute_at_root(&r,goal,false).unwrap_err().starts_with("APPROVAL_REQUIRED"));let ok=execute_at_root(&r,goal,true).unwrap();assert!(ok.verified);assert_eq!(fs::read_to_string(target).unwrap(),"REPLACEMENT");fs::remove_dir_all(r).unwrap();}}
