export type CapabilityState="verified"|"partial"|"untested"|"unavailable";
export interface GpuSnapshot{name:string;utilizationPercent:number|null;temperatureC:number|null;memoryUsedMb:number|null;memoryTotalMb:number|null}
export interface DiskSnapshot{mount:string;totalGb:number;freeGb:number}
export interface GovernorSnapshot{available:boolean;state:string|null;source:string|null;foregroundGame:string|null;detectionReason:string|null;detectionConfidence:number|null;cpuPercent:number|null;ramPercent:number|null;gpuPercent:number|null;gpuTempC:number|null;gatewayPingMs:number|null;internetPingMs:number|null;cpuGuardMode:string|null;restrainedProcesses:string[];hags:string|null}
export interface OpenCodeSnapshot{available:boolean;version:string|null;endpoint:string}
export interface ProtocolInspection{sourceAvailable:boolean;sourceFingerprint:string|null;lineCount:number;handlerCandidates:string[];commandCandidates:string[];safeProbeCandidates:string[];framingSignals:string[];protocolSignals:string[];encoding:string;discriminatorField:string|null;framingMode:string;pipeCandidates:string[];requestPipeFromSource:string|null;eventPipeFromSource:string|null;confidence:number;probeReady:boolean;probeReason:string}
export interface LegacyAgentSnapshot{sourcePath:string;sourceAvailable:boolean;pipeServerSourceAvailable:boolean;requestPipe:string;requestPipeAvailable:boolean;eventPipe:string;eventPipeAvailable:boolean;protocolHint:string;protocol:ProtocolInspection}
export interface ReadOnlyProbeResult{allowed:boolean;attempted:boolean;transportVerified:boolean;semanticOk:boolean;reason:string;command:string|null;discriminatorField:string|null;framingMode:string;requestPipe:string;elapsedMs:number;responseRaw:string|null;responseJson:unknown|null}
export interface DeviceSnapshot{capturedAt:string;hostname:string;os:string;cpuName:string;cpuUsagePercent:number;logicalCpus:number;ramTotalGb:number;ramUsedGb:number;ramUsagePercent:number;gpu:GpuSnapshot|null;disks:DiskSnapshot[];processCount:number;runningApps:string[];governor:GovernorSnapshot;openCode:OpenCodeSnapshot;legacyAgent:LegacyAgentSnapshot}
export interface CapabilitySnapshot{id:string;label:string;state:CapabilityState;evidence:string}
export interface RuntimeStatus{paused:boolean;uptimeSeconds:number;native:boolean;version:string}
export interface RuntimeOverview{runtime:RuntimeStatus;device:DeviceSnapshot;capabilities:CapabilitySnapshot[]}
export interface MissionStepResult{title:string;status:string;evidence:string|null}
export interface MissionEvidence{kind:string;claim:string;value:string;verified:boolean}
export interface MissionResult{id:string;goal:string;status:string;qualityScore:number;targetPath:string|null;verified:boolean;steps:MissionStepResult[];evidence:MissionEvidence[]}
export interface RuntimeMission{id:string;goal:string;status:string;executor:string;selectedModes:string[];result:MissionResult|null;approvalId:string|null;updatedAt:number}
export interface ApprovalRequest{id:string;missionId:string;goal:string;action:string;reason:string;risk:string;targetPath:string;status:string;createdAt:number}
export interface ModeDefinition{id:string;name:string;purpose:string;priority:number;requiredCapabilities:string[]}
